spring:
  datasource:
    url: jdbc:h2:mem:sales
    username: sales
    password: sales
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console.enabled: true
  flyway:
    baseline-on-migrate: true